name: CI
on: [push, pull_request]

jobs:

  package-haxelib:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: actuate-haxelib
          path: |
            ./
            !test/
            !scripts/
            !lib/
            !lib-esm/
            !haxe-*-*/
            !neko-*-*/
            !.git/
            !webpack.*
            !package.json
          if-no-files-found: error

  docs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install dox --quiet
          haxelib dev actuate ${{ github.workspace }}

      - name: Build docs
        working-directory: scripts
        run: |
          haxe docs.hxml

      - uses: actions/upload-artifact@v4
        with:
          name: actuate-docs
          path: docs
          if-no-files-found: error

  build-npm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@4
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: |
        npm install

    - name: Build Library
      run: |
        npm run build

    - name: Package Library for npm
      run: |
        npm pack

    - uses: actions/upload-artifact@v4
      with:
        name: actuate-npm
        path: actuate-*.tgz
        if-no-files-found: error